Sort colors
MIT-Emerging-Talent/ET6-foundations-group-24 pull request #52
Opened 2024-12-29 21:07 UTC by Mohamed-Elnageeb

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2024-12-30 20:06 UTC, linahKhayri reviewed
Hey Mohamed, reviewing your code was a good experience, at first I thought the problem might be something new to me, but the comments at each step and the docstring explaining the behavior of your code helped me understand everything and it turned out simple!. It’s well-organized and structured, and it passed all the checklists
great job! 👌
I just added a few comments in some lines of the code that I thought would make it clearer, but over all it's AMAZING👏

2024-12-30 22:41 UTC, Mohamed-Elnageeb commented on solutions/tests/test_sort_colors.py
> +    def test_randomly_generated_list(self):
Ok thanks....also I think I will remove this test as i realised this can fall under "using logic in a unit test".

2024-12-30 22:42 UTC, Mohamed-Elnageeb commented on solutions/sort_colors.py
> +    counter_array = [0] * 3
Ok,Will do tomorrow 😇

2024-12-31 17:36 UTC, linahKhayri submitted a review, later dismissed
Good job Mohamed👏

2024-12-31 19:41 UTC, GaiSamuel requested changes
Well, elaborated! I have suggested just a few changes and enquired an explanation on line 91-92

2024-12-31 19:41 UTC, GaiSamuel commented on solutions/sort_colors.py
> +    # Rebuild the nums array in-place
This too, "array" to "list"

2025-01-01 09:02 UTC, Mohamed-Elnageeb commented on solutions/tests/test_sort_colors.py
> +if __name__ == "__main__":
This statement "if __name__ == "__main__"  is used when you want code executed only when a file is run as a script rather than imported as a module. 
So i want the tests to run.and btw when i tried witgout it i got py_tests errors during CI checks.

2025-01-01 09:03 UTC, Mohamed-Elnageeb commented on solutions/sort_colors.py
> +    # Create a counter array to store the count of each number
Ok

2025-01-01 17:13 UTC, GaiSamuel commented on solutions/tests/test_sort_colors.py
> +if __name__ == "__main__":
oh alright.

2025-01-03 13:28 UTC, Khusro-S approved these changes
This function basically sorts a list, which is only supposed to contain numbers `0`, `1`, and `2`. The counter_list counts how many `0`s, `1`s, and `2`s are in the list. Then, it places those numbers back into the original list in sorted order.

For example, if our input list is:
`[1, 1, 2, 1, 0, 0, 1]`

The counter_list will count the occurrences of each number:
`counter_list = [2, 4, 1]`

This means there are two `0`s, four `1`s, and one `2`  in the list.
Next, the rebuilding part places the numbers back into the original list. Here's how it works step by step:

1. Start by adding all the `0`s → `[0, 0, 2, 1, 0, 0, 1]`
2. Then, add all the `1`s → `[0, 0, 1, 1, 1, 1, 1]`
3. Finally, add the `2`s → `[0, 0, 1, 1, 1, 1, 2]`
The final sorted list is:
`[0, 0, 1, 1, 1, 1, 2]`

This explanation is just to help me understand the implementation and confirm whether I’ve understood it correctly. Please let me know if I missed anything or got something wrong.

 I really liked how this implementation avoids using built-in sorting functions and sticks to an efficient and straightforward counting sort approach. The logic is super clear, and the in-place sorting is a nice touch! Great job! 🎉

2025-01-03 13:28 UTC, Khusro-S commented on solutions/tests/test_sort_colors.py
> +
Yea I agree, would make it more easier to differentiate between the cases but at the same time, might be redundant 🤔

2025-01-03 13:28 UTC, Khusro-S commented on solutions/tests/test_sort_colors.py
> +        self.assertEqual(nums, expected)
Even though it is okay but maybe try hardcoding the values, but then it'd probably be hundreds or thousands of lines of code 🤔.... yea this might be better in this situation nvm😄

2025-01-03 16:33 UTC, GaiSamuel approved these changes
Looks good. Great work.

2025-01-03 18:37 UTC, merged