Ascii code
MIT-Emerging-Talent/ET6-foundations-group-24 pull request #65
Opened 2024-12-31 06:59 UTC by Zeinab15

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2025-01-03 13:46 UTC, Khusro-S requested changes
Overall, the code is pretty self-explanatory, clean, and nicely written. I just suggested a few small changes that I think would make things even clearer or more helpful 🎉

2025-01-03 13:46 UTC, Khusro-S commented on solutions/ascii_code.py
> +    return c
The variable name `c` doesn't clearly explain what it's for. It would be better to rename it to something like `ascii_values` or `unicode_codes`. This will make the code easier to understand, as the name will show that the list is holding the `ASCII` or `Unicode` values of the characters in the string.

2025-01-03 13:46 UTC, Khusro-S commented on solutions/ascii_code.py
> +    ascii_code('0') -> [48]
```suggestion
    Example:
    >>> ascii_code('abc')
    [97, 98, 99]
    
    >>> ascii_code('!')
    [33]
    
    >>> ascii_code('')
    []
    
    >>> ascii_code(' ')
    [32]
    
    >>> ascii_code('0')
    [48]
```

2025-01-03 13:46 UTC, Khusro-S commented on solutions/ascii_code.py
> +    ascii_code('0') -> [48]
This change will allow you to test the doctests. Previously, it was just a docstring without the ability to run tests.

2025-01-03 15:43 UTC, GaiSamuel requested changes
Most of the code looks however some arrears would need  changes and i have suggested a few.

2025-01-03 15:43 UTC, GaiSamuel commented on solutions/ascii_code.py
> +    AssertionError: if the input is an empty string (no characters) e.g. ascii_code("")
ascii_code("") wouldn't raise an assertion error since you modified it in the function in line 45 and for the rest, like ascii_code(123) or ascii_code(12.3) those are invalid inputs and wouldn't raise assertion error but type error. So line 29 and 30 need to be deleted.


![Screenshot (67)](https://github.com/user-attachments/assets/b4d4b6b5-b941-4f33-b2bf-8bd795da3bfc)

2025-01-03 15:43 UTC, GaiSamuel commented on solutions/tests/test_ascii_code.py
> +        """Test handling of number input."""
The docstring needs to be changed to testing invalid input since the test is an invalid input. The rest of the tests from 64-74 are invalid inputs as well and return type error instead. So it would be better if they were all under one test.

![Screenshot (65)](https://github.com/user-attachments/assets/ef4b1781-e75c-4f74-a92e-9b9a906b56ea)

2025-01-03 15:51 UTC, GaiSamuel commented on solutions/ascii_code.py
> +        raise AssertionError("Input must be a string")
would raise type error not assertion error.

2025-01-04 10:09 UTC, GaiSamuel approved these changes

2025-01-05 12:23 UTC, Khusro-S approved these changes

2025-01-05 12:23 UTC, Khusro-S commented on solutions/tests/test_ascii_code.py
> +    def test_None_input(self):
To keep the naming style consistent, I noticed that `test_None_input` doesn’t fully follow the snake_case convention, all the letters should ideally be lowercase, like `test_none_input`. Not a big deal, but I thought it’d be worth mentioning 😅

2025-01-05 13:13 UTC, merged