check anagram done and ready for review
MIT-Emerging-Talent/ET6-foundations-group-24 pull request #66
Opened 2024-12-31 11:16 UTC by TekaMesfinAbel

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2025-01-01 18:04 UTC, ViktoriyaHaiduk submitted a review, later dismissed
Great job on the implementation! Your function is well-structured, and the documentation clearly explains how it works. Overall, the code is clean, concise, and easy to understand. Keep up the good work!

2025-01-01 18:04 UTC, ViktoriyaHaiduk commented on solutions/check_anagram.py
> +"""
Please add header due to Evan's example:
https://github.com/MIT-Emerging-Talent/ET6-Programming-With-Python/tree/main/3_documenting_and_testing/examples

2025-01-02 06:03 UTC, TekaMesfinAbel commented on solutions/check_anagram.py
> +"""
Thank you viktoriya. I will do that.

2025-01-02 08:25 UTC, ViktoriyaHaiduk approved these changes
Great job on the implementation!

2025-01-02 14:53 UTC, GaiSamuel requested changes
Looks good generally. Just a few corrections added.

2025-01-02 14:53 UTC, GaiSamuel commented on solutions/check_anagram.py
> +        TypeError: If either argument is not a string.
Raises Attribute error not type error according to the test provided.

2025-01-02 14:53 UTC, GaiSamuel commented on solutions/tests/test_check_anagram.py
> +        with self.assertRaises(TypeError):
Raises attribute error not type error.

2025-01-02 14:53 UTC, GaiSamuel commented on solutions/tests/test_check_anagram.py
> +        with self.assertRaises(TypeError):
Raises attribute error not type error.

2025-01-03 06:19 UTC, TekaMesfinAbel commented on solutions/check_anagram.py
> +        TypeError: If either argument is not a string.
Ohh yeah. Thanks for catching that.

2025-01-03 10:19 UTC, ViktoriyaHaiduk approved these changes
Good job. Everything is according to checklist.

2025-01-03 11:54 UTC, GaiSamuel approved these changes
Looks good! Great work Abel.

2025-01-03 11:57 UTC, ViktoriyaHaiduk approved these changes
Great job on the implementation! Your function is well-structured, and the documentation clearly explains how it works. Overall, the code is clean, concise, and easy to understand. Keep up the good work!

2025-01-03 15:42 UTC, merged