Intersection of two
MIT-Emerging-Talent/ET6-foundations-group-24 pull request #67
Opened 2024-12-31 11:19 UTC by linahKhayri

---
name: solution review of intersection_of_two function
about: A template PR for code review with a checklist
---

 [here's the issue](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-24/issues/53)

This function takes two lists and returns a list containing the intersection of them.
    The intersection includes only the items that are present in both
    list1 and list2. The items in the intersection are returned only once,
    even if they appear multiple times in the input lists. The input lists
    can contain any type of items that are allowed in a list (e.g., integers,
    strings, floats, special characters, etc.)

    Note:
        The function could be simplified using built-in functions like set(),
        which automatically handle duplicates and set intersections.
        However, I wanted to write the logic manually to demonstrate how it works step-by-step

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2025-01-01 12:07 UTC, robiel0143 approved these changes
Well prepared.

2025-01-01 17:59 UTC, ViktoriyaHaiduk commented on solutions/tests/test_intersection_of_two.py
> +            intersection_of_two(first_list, second_list2)
Great work! Everything is ok!

2025-01-01 17:59 UTC, ViktoriyaHaiduk submitted a review, later dismissed
Great work! Everything is ok!

2025-01-02 11:01 UTC, linahKhayri commented
> Great work! Everything is ok!

Thank you so much @ViktoriyaHaiduk for the feedback 💖
Can you please do the checks in the pr checklist?

2025-01-03 20:20 UTC, Mohamed-Elnageeb requested changes
Good clean code linah! 
only small changes needed.

2025-01-03 20:20 UTC, Mohamed-Elnageeb commented on solutions/intersection_of_two.py
> +    for item in first_list:
I like the strategy behind your solution. However, the implementation could potentially be optimized for better performance by using sets instead of lists. That said, this change is not strictly necessary

2025-01-03 20:20 UTC, Mohamed-Elnageeb commented on solutions/intersection_of_two.py
> +    assert isinstance(first_list, list), "first list must be a list"
here in the comments i think you should write the name of the variable to make the meaning more clear : 
i.e first_list must be a list

2025-01-03 20:20 UTC, Mohamed-Elnageeb commented on solutions/tests/test_intersection_of_two.py
> +    - Defensive tests: Non-list inputs, one empty list, both empty lists
good well-rounded tests

2025-01-03 22:12 UTC, linahKhayri commented on solutions/intersection_of_two.py
> +    for item in first_list:
Thank you Mohamed,🙏
Indeed it may give faster results but I included this in the function docstring as a note: `(This function could be simplified using built-in functions like set(), 
        which automatically handle duplicates and set intersections.
        However, I wanted to write the logic manually to demonstrate how it works step-by-step) `
So I used a loop instead of the built in set() function just to show how the process works step-by-step. But if you're talking about using sets as inputs instead of lists, that's actually a great idea and might be the better choice but I just wanted to manually handle the duplicate elements and show how they get executed once.

2025-01-03 22:16 UTC, linahKhayri commented on solutions/intersection_of_two.py
> +    assert isinstance(first_list, list), "first list must be a list"
Done, thankss 💖

2025-01-03 22:17 UTC, Mohamed-Elnageeb commented on solutions/intersection_of_two.py
> +    for item in first_list:
oh ok i missed that one! good 👍

2025-01-03 22:18 UTC, Mohamed-Elnageeb approved these changes

2025-01-03 22:24 UTC, linahKhayri commented
> Good clean code linah! only small changes needed.

Thank you so much, I really appreciate the feedback 💖

2025-01-06 11:14 UTC, merged